### ISSUE TITLE
TimeTableWindowの実装

### ISSUE THREAD

**Issue by ItisNoMatter** [ItisNoMatter/cist-cat-android#5]
## 概要
figmaでAtomsとして定義されている「TimeTableWindow」 を実装する
![image](https://user-images.githubusercontent.com/41831807/223149727-7c0b1499-9c04-4d63-ab61-be70a53e22ad.png)

## TODO
1. TimeTableWindow.ktファイルを[atomsディレクトリ](https://github.com/ItisNoMatter/cist-cat-android/blob/11198bf40bc7f29930b04b9f8c190140c5440cd8/app/src/main/java/com/example/cist_cat/atoms)下に作成
2. [composableな関数](https://developer.android.com/jetpack/compose/tutorial?hl=ja#define-a-composable-function)としてDirectionToggle()を実装
3. 2.を呼び出すだけのTimeTableWindowも実装し、@previewアノテーションを付ける
4. Preview結果をスクリーンショットしてこのissueにアップロード

## 補足
TimeTableWindow関数は[scrollable](https://developer.android.com/jetpack/compose/gestures?hl=ja#scroll-modifiers)にしてください。
表示する時刻はとりあえずダミーのものでよいです。

**Comment by 618knot** [comment]
![Screenshot_20230316_181335](https://user-images.githubusercontent.com/82982400/225570850-be62eca4-471b-4cf2-b245-7d79f7f10ca4.png)

- *がつくとレイアウトがおかしい
- スクロールバーがない
